name: Run Apex PMD

on:
  pull_request:
    branches:
      - QA

jobs:
  apexPMD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache PMD
        uses: actions/cache@v2
        with:
          path: ~/pmd-bin-6.29.0
          key: ${{ runner.os }}-pmd-${{ hashFiles('**/pmd-bin-6.29.0') }}

      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.29.0/pmd-bin-6.29.0.zip
          unzip pmd-bin-6.29.0.zip -d ~/

      - name: Run PMD
        run: |
          ~/pmd-bin-6.29.0/bin/run.sh pmd -d src/classes -R src/config/ruleset.xml -f textcolor

